repos:
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --strict gamepack/
        language: system
        pass_filenames: false
        files: ^gamepack/.*\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: fix-byte-order-marker
