from collections.abc import Callable as Callable
from typing import Self

from gamepack.MDPack import MDObj as MDObj

class BaseCharacter:
    errors: list[str]
    def __init__(self) -> None: ...
    @classmethod
    def from_mdobj(cls, mdobj: MDObj, flash_func: Callable[[str], None] | None = None) -> Self: ...
    def to_mdobj(self) -> MDObj: ...
    def to_md(self) -> str: ...
