import ast
from collections.abc import Callable as Callable
from typing import Any

from _typeshed import Incomplete

NodeTypes: Incomplete

def eval_node(node: ast.expr | NodeTypes, variables: frozenset[tuple[str, Any]]) -> float: ...
def eval_expression(node: ast.Expression, variables: frozenset[tuple[str, Any]]) -> float: ...
def eval_constant(node: ast.Constant, variables: frozenset[tuple[str, Any]]) -> float: ...
def eval_name(node: ast.Name, variables: frozenset[tuple[str, Any]]) -> float: ...
def eval_binop(node: ast.BinOp, variables: frozenset[tuple[str, Any]]) -> float: ...
def eval_unaryop(node: ast.UnaryOp, variables: frozenset[tuple[str, Any]]) -> float: ...

EVALUATORS: Incomplete
UNARY_OPERATIONS: dict[type, Callable[[Any], Any]]
BINARY_OPERATIONS: dict[type, Callable[[Any, Any], Any]]
binary_whitespace_op: Incomplete

def evaluate(expression: str, variables: frozenset[tuple[str, Any]]) -> float: ...
