import ast
from collections.abc import Callable as Callable
from typing import Any

from _typeshed import Incomplete

NodeTypes = ast.Expression | ast.Constant | ast.Name | ast.BinOp | ast.UnaryOp

def eval_node(node: ast.expr | NodeTypes, variables: frozenset[tuple[str, float | int]]) -> float: ...
def eval_expression(node: ast.Expression, variables: frozenset[tuple[str, float | int]]) -> float: ...
def eval_constant(node: ast.Constant, variables: frozenset[tuple[str, float | int]]) -> float: ...
def eval_name(node: ast.Name, variables: frozenset[tuple[str, float | int]]) -> float: ...
def eval_binop(node: ast.BinOp, variables: frozenset[tuple[str, float | int]]) -> float: ...
def eval_unaryop(node: ast.UnaryOp, variables: frozenset[tuple[str, float | int]]) -> float: ...

EVALUATORS: dict[type, Callable[[Any, frozenset[tuple[str, float | int]]], float]]
UNARY_OPERATIONS: dict[type, Callable[[Any], float]]
BINARY_OPERATIONS: dict[type, Callable[[Any, Any], float]]
binary_whitespace_op: Incomplete

def evaluate(expression: str, variables: frozenset[tuple[str, float | int]]) -> float: ...
