from collections import deque

from _typeshed import Incomplete

from gamepack.Dice import Dice

logger: Incomplete
math_formula_regex: Incomplete
numbers_and_commas: Incomplete

def tuple_overlap(a: tuple[int, int], b: tuple[int, int]) -> bool: ...

class Node:
    special: tuple[list[str], list[str], list[str]]
    do: bool
    code: Incomplete
    depth: Incomplete
    dependent: dict[tuple[tuple[int, int], str], Node]
    def __init__(self, roll: str, depth: int) -> None: ...
    def rebuild(self) -> None: ...
    def buildroll(self) -> None: ...
    def calculate(self) -> None: ...
    @staticmethod
    def calc(to_calculate: str | list[str]) -> str: ...

class DiceParser:
    last_parse: DiceParser | None
    rolllogs: deque[Dice]
    dice_expression_parser: Incomplete
    dbg: str
    triggers: Incomplete
    rights: Incomplete
    defines: Incomplete
    define_regex: Incomplete
    last_rolls: Incomplete
    messages: list[str]
    def __init__(self, defines=None, lastroll=None, lastparse=None) -> None: ...
    def update_define_regex(self) -> None: ...
    usage: str
    @classmethod
    def extract_diceparams(cls, message) -> None: ...
    def do_roll(self, roll, depth: int = 0) -> Dice: ...
    def make_roll(self, roll: str) -> Dice: ...
    def resolveroll(self, roll: Node | str, depth) -> Node: ...
    def resonances(self, rolls: list[Dice] | None = None) -> list[dict[int, int]]: ...
    def project(self, body: str) -> str: ...
    def triggerswitch(self, triggername, triggerbody) -> None: ...
    @staticmethod
    def gettriggers(message) -> list[str]: ...
    def pretrigger(self, roll: str) -> tuple[str, bool]: ...
    def resolvedefines(self, roll: Node, used: list[str] | None = None) -> None: ...

def fullparenthesis(text: str, opening: str = "(", closing: str = ")", *, include: bool = False) -> str: ...
def fast_fullparenthesis(text: str) -> str: ...
