from typing import Any

from _typeshed import Incomplete

from gamepack.Dice import DiceParams

class DiceExpressionParser:
    tokens: Incomplete
    def p_expression_with_selectors(self, p: Any) -> None: ...
    def p_expression_no_selectors(self, p: Any) -> None: ...
    def p_selectors_multiple(self, p: Any) -> None: ...
    def p_selectors_single(self, p: Any) -> None: ...
    def p_selector_num(self, p: Any) -> None: ...
    def p_selector_neg(self, p: Any) -> None: ...
    def p_dice_expr_with_suffix(self, p: Any) -> None: ...
    def p_dice_expr_amount_only(self, p: Any) -> None: ...
    def p_amount_num(self, p: Any) -> None: ...
    def p_amount_neg_num(self, p: Any) -> None: ...
    def p_amount_minus_seq(self, p: Any) -> None: ...
    def p_amount_literal(self, p: Any) -> None: ...
    def p_literal_list_multiple(self, p: Any) -> None: ...
    def p_literal_list_single(self, p: Any) -> None: ...
    def p_literal_item_num(self, p: Any) -> None: ...
    def p_literal_item_neg(self, p: Any) -> None: ...
    def p_dice_suffix_d(self, p: Any) -> None: ...
    def p_dice_suffix_no_d(self, p: Any) -> None: ...
    def p_sides(self, p: Any) -> None: ...
    def p_options_multiple(self, p: Any) -> None: ...
    def p_options_empty(self, p: Any) -> None: ...
    def p_option_reroll(self, p: Any) -> None: ...
    def p_option_reroll_neg(self, p: Any) -> None: ...
    def p_option_sort(self, p: Any) -> None: ...
    def p_option_success(self, p: Any) -> None: ...
    def p_option_full_success(self, p: Any) -> None: ...
    def p_option_sum(self, p: Any) -> None: ...
    def p_option_max(self, p: Any) -> None: ...
    def p_option_min(self, p: Any) -> None: ...
    def p_option_none(self, p: Any) -> None: ...
    def p_option_id(self, p: Any) -> None: ...
    def p_option_explosion(self, p: Any) -> None: ...
    def p_error(self, p: Any) -> None: ...
    lexer: Incomplete
    parser: Incomplete
    def __init__(self) -> None: ...
    def parse(self, data: str) -> DiceParams: ...
