from _typeshed import Incomplete

class DescriptiveError(Exception): ...
class DiceCodeError(Exception): ...

logger: Incomplete

class Dice:
    returnfun: str | None
    sign: int
    r: Incomplete
    min: Incomplete
    explosions: int
    literal: bool
    amount: Incomplete
    max: Incomplete
    difficulty: Incomplete
    subone: Incomplete
    explodeon: Incomplete
    sort: Incomplete
    rerolls: Incomplete
    log: str
    dbg: str
    comment: str
    show: bool
    rolled: bool
    def __init__(
        self,
        amount: list[int] | int | None,
        sides: int,
        difficulty: int | None = None,
        onebehaviour: int = 0,
        returnfun: str | None = None,
        explosion: int = 0,
        minimum: int = 1,
        *,
        sort: bool = False,
        rerolls: int = 0,
        **kwargs: dict,
    ) -> None: ...
    def resonance(self, resonator: int): ...
    def __repr__(self) -> str: ...
    @property
    def name(self) -> None: ...
    def another(self) -> None: ...
    def rolldie(self) -> None: ...
    def modified_amount(self, amount) -> None: ...
    def process_rerolls(self) -> None: ...
    def roll_next(self, amount=None) -> None: ...
    @staticmethod
    def botchformat(succ, antisucc) -> None: ...
    def roll_wodsuccesses(self) -> int: ...
    def roll_v(self) -> str: ...
    def roll_sel(self) -> None: ...
    def __int__(self) -> int: ...
    @property
    def result(self) -> int | None: ...
    def roll(self, amount=None) -> None: ...
    @classmethod
    def empty(cls) -> Dice: ...
