def montecarlo(roll, run_for: int = 10): ...
def plot(
    data: dict[int, int], *, showsucc: bool = False, showgraph: bool = True, showdmgmods: bool = False, grouped: int = 1
) -> str: ...
def ascii_graph(occurrences: dict, mode: int) -> tuple[str, float, float]: ...
def avgdev(occurrences) -> tuple[float, float]: ...
