def montecarlo(roll: str, run_for: int = 10) -> str: ...
def plot(
    data: dict[int, int], *, showsucc: bool = False, showgraph: bool = True, showdmgmods: bool = False, grouped: int = 1
) -> str: ...
def ascii_graph(occurrences: dict[int, int], mode: int) -> tuple[str, float, float]: ...
def avgdev(occurrences: dict[int, int]) -> tuple[float, float]: ...
