from collections import OrderedDict
from collections.abc import Callable as Callable
from typing import Any, ClassVar, Self

from gamepack.BaseCharacter import BaseCharacter
from gamepack.Item import Item
from gamepack.MDPack import MDObj

__author__: str

class FenCharacter(BaseCharacter):
    Inventory: list[Item]
    description_headings: ClassVar[list[str]]
    value_headings: ClassVar[list[str]]
    inventory_headings: ClassVar[list[str]]
    halfpoint_sections: ClassVar[list[str]]
    fullpoint_sections: ClassVar[list[str]]
    onepoint_sections: ClassVar[list[str]]
    experience_headings: ClassVar[list[str]]
    wound_headings: ClassVar[list[str]]
    note_headings: ClassVar[list[str]]
    concept_headings: ClassVar[list[str]]
    Inventory_Bonus_Headers: set[str]
    definitions: dict[str, str]
    Tags: str
    Character: dict[str, Any]
    Meta: OrderedDict[str, MDObj]
    Categories: dict[str, Any]
    Notes: MDObj
    Storage: str
    Timestamp: str
    xp_cache: dict[str, int]
    headings_used: dict[str, Any]
    def __init__(self) -> None: ...
    def stat_definitions(self) -> dict[str, str]: ...
    @staticmethod
    def cost(att: tuple[int, ...], internal_costs: list[int], internal_penalty: list[int]) -> int: ...
    @staticmethod
    def cost_calc(inputstring: str, width: int = 3) -> int | list[list[int]]: ...
    def magicwidth(self, name: str) -> int: ...
    def points(self, name: str) -> int: ...
    def get_xp_for(self, name: str) -> int: ...
    @staticmethod
    def parse_xp(s: str) -> int: ...
    def add_xp(self, name: str, value: int) -> int: ...
    @staticmethod
    def recursive_category_handle(category: MDObj) -> tuple[dict[str, Any], dict[str, Any] | list[str]]: ...
    @classmethod
    def from_mdobj(cls, mdobj: MDObj, flash_func: Callable[[str], None] | None = None) -> Self: ...
    @classmethod
    def construct_mdobj_from_category(
        cls, category_dict: dict[str, Any], headings: dict[str, Any] | list[str], flash_func: Callable[[str], None]
    ) -> MDObj: ...
    def to_mdobj(self, flash_func: Callable[[str], None] | None = None) -> MDObj: ...
    @classmethod
    def from_md(cls, body: str, flash: Callable[[str], None] | None = None) -> Self: ...
    def to_md(self, flash: Callable[[str], None] | None = None) -> str: ...
    def post_process(self, flash: Callable[[str], None]) -> None: ...
    def process_inventory(self, node: MDObj, flash: Callable[[str], None]) -> None: ...
    def process_xp(self, node: MDObj) -> None: ...
    def inventory_table(self) -> list[list[str]]: ...
