import io

from _typeshed import Incomplete

log: Incomplete

def fastdata(selector: tuple[int, ...], mod: int) -> dict[int, int]: ...
def fastversus(selector1: tuple[int, ...], selector2: tuple[int, ...], mod1: int, mod2: int) -> dict[int, int]: ...
def versus(
    selectors1: tuple[int, ...], selectors2: tuple[int, ...], mod1: int = 0, mod2: int = 0, mode: int = 0
) -> tuple[str, float, float]: ...
def modify_dmg(specific_modifiers: list[float], dmg: list[list[int]], damage_type: str, armor: float) -> float: ...
def rawload(page: str) -> str: ...
def chances(
    selector: tuple[int, ...],
    modifier: int = 0,
    number_of_quantiles: int | None = None,
    mode: int = 0,
    *,
    interactive: bool = False,
) -> tuple[str, float, float] | io.BytesIO: ...
def count_sorted_rolls(num_dice: int, num_sides: int) -> dict[tuple[int, ...], int]: ...
def count_lowest_rolls(counts: dict[tuple[int, ...], int], subselection: int) -> dict[tuple[int, ...], int]: ...

basesets: Incomplete
freq_dicts: Incomplete
