from _typeshed import Incomplete

log: Incomplete

def fastdata(selector: tuple[int, ...], mod: int) -> dict[int, int]: ...
def fastversus(selector1: tuple[int, ...], selector2: tuple[int, ...], mod1: int, mod2: int) -> dict[int, int]: ...
def versus(selectors1: tuple[int, ...], selectors2: tuple[int, ...], mod1: int = 0, mod2: int = 0, mode: int = 0): ...
def modify_dmg(specific_modifiers, dmg, damage_type, armor) -> None: ...
def rawload(page) -> str: ...
def chances(
    selector: tuple[int, ...], modifier: int = 0, number_of_quantiles=None, mode: int = 0, *, interactive: bool = False
): ...
def count_sorted_rolls(num_dice, num_sides) -> None: ...
def count_lowest_rolls(counts, subselection) -> None: ...

basesets: Incomplete
freq_dicts: Incomplete
