from typing import Any, ClassVar

from _typeshed import Incomplete

from gamepack.endworld.System import System

class HeatSystem(System):
    headers: ClassVar[list[str]]
    systype: str
    capacity: float
    passive: str
    active: str
    current: float
    flux_used: float
    active_flux: float
    passive_flux: float
    def __init__(self, name: str, data: dict[str, Any]) -> None: ...
    @property
    def flux(self) -> float: ...
    @flux.setter
    def flux(self, value: float): ...
    @property
    def flux_remaining(self) -> float: ...
    def reset_ephemeral(self) -> None: ...
    def unpack(self, inp: str) -> tuple[float, float]: ...
    enabled: Incomplete
    def use(self, parameter: str | None) -> float: ...
    def to_dict(self) -> dict: ...
    def spare_capacity(self) -> float: ...
    def add_heat(self, amt: float) -> float: ...
    def withdraw_heat(self, amt: float) -> float: ...
    def tick(self) -> float: ...
