from collections.abc import Callable, Sequence
from typing import Any

from _typeshed import Incomplete

log: Incomplete

class MDListItem:
    text: Incomplete
    bullet: Incomplete
    checked: Incomplete
    level: Incomplete
    def __init__(self, text: str, bullet: str = "-", checked: bool | None = None, level: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class MDList:
    LIST_PATTERN: Incomplete
    items: Incomplete
    position: Incomplete
    def __init__(self, items: list[MDListItem], position: int | None = None) -> None: ...
    def to_md(self) -> str: ...
    @property
    def checklist(self) -> list[tuple[str, bool]]: ...
    @classmethod
    def from_md(cls, md_text: str, position: int | None = None) -> MDList: ...
    @classmethod
    def extract_lists(cls, plaintext: str) -> tuple[str, list[MDList]]: ...
    @classmethod
    def insert_lists(cls, text: str, lists: Sequence[MDList]) -> str: ...

class MDChecklist(MDList):
    CHECKBOX_PATTERN: Incomplete
    def __init__(self, checklist: list[tuple[str, bool]], position: int | None = None) -> None: ...
    @classmethod
    def from_md(cls, md_text: str, position: int | None = None) -> MDChecklist: ...
    @classmethod
    def extract_checklists(cls, plaintext: str) -> tuple[str, list[MDChecklist]]: ...
    @classmethod
    def insert_checklists(cls, text: str, checklists: list[MDChecklist]) -> str: ...

class MDTable:
    rows: list[list[str]]
    headers: list[str]
    style: list[str | None]
    prev_line_nr: int | None
    def __init__(self, rows: list[list[str]], headers: list[str], style: list[str | None] | None = None) -> None: ...
    @staticmethod
    def split_row(row: str, length: int) -> list[str]: ...
    def row_as_dict(self, row_idx: int) -> dict[str, str]: ...
    @staticmethod
    def extract_styles(row: list[str]) -> list[str | None]: ...
    def row(self, key: str) -> dict[str, str] | None: ...
    @classmethod
    def from_md(cls, md: str) -> MDTable: ...
    def to_md(self) -> str: ...
    @property
    def rows_dict(self) -> dict[str, dict[str, str]]: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def line_align(line: str, align: str | None, length: int) -> str: ...
    def search(self, searchterm: str) -> list[str] | None: ...
    def to_simple(self) -> dict[str, Any]: ...
    def update_cell(self, row: int, col: int, data: str): ...
    def update_rows(self, data: list[list[str]]): ...
    def clear_rows(self) -> None: ...
    def canonize(self) -> None: ...
    def __getitem__(self, key: str) -> str | None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def column(self, key: str, default: list[str] | None = None) -> list[str]: ...
    def header_pos(self, possible_headers: list[str], default: int = -1) -> int: ...
    @classmethod
    def extract_tables(cls, plaintext: str) -> tuple[str, list[MDTable]]: ...
    @classmethod
    def insert_tables(cls, text: str, tables: list[MDTable]) -> str: ...

class MDObj:
    originalMD: str
    plaintext: Incomplete
    tables: Incomplete
    lists: Incomplete
    children: dict[str, MDObj]
    level: Incomplete
    header: Incomplete
    errors: list[str]
    flash: Incomplete
    def __init__(
        self,
        plaintext: str,
        children: dict[str, MDObj] | None = None,
        flash: Callable[[str], None] | None = None,
        tables: list[MDTable] | None = None,
        level: int = 0,
        header: str = "",
        original: str | None = None,
        lists: list[MDList] | None = None,
        checklists: list[MDChecklist] | None = None,
    ) -> None: ...
    @property
    def checklists(self) -> list[MDChecklist]: ...
    def add_to_error(self, error: str): ...
    @property
    def all_checklists(self) -> list[tuple[str, bool]]: ...
    def search_checklist_with_path(self, name: str, path: list[str] | None = None) -> list[list[str]]: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    @classmethod
    def from_md(
        cls, lines: str | list[str], level: int = 0, header: str = "", flash: Callable[[str], None] | None = None
    ) -> MDObj: ...
    def confine_to_tables(self, *, horizontal: bool = False) -> tuple[dict[str, Any], list[str]]: ...
    def search_children(self, name: str) -> MDObj | None: ...
    def set_levels(self, newlevel: int | None = None): ...
    def add_child(self, child: MDObj) -> MDObj: ...
    def is_ancestor(self, child: MDObj) -> bool: ...
    def add_children(self, children: list[MDObj]) -> MDObj: ...
    def to_md(self, *, do_header: bool = True) -> str: ...
    def search_tables(self, searchterm: str) -> MDTable | None: ...
    def replace_content_by_path(self, path: list[str], new_content: str): ...
    def get_content_by_path(self, path: list[str]) -> MDObj: ...
    def with_header(self, header_text: str) -> MDObj: ...
    @classmethod
    def empty(cls) -> MDObj: ...

def table_row_edit(md: str, key: str, value: str) -> str: ...
def table_md(t: list[list[str]]) -> str: ...
def table_add(md: str, key: str, new_val: str) -> str: ...
def table_remove(md: str, key: str) -> str: ...
def search_tables(md: str, seek: str, surround: int | None = None) -> str: ...
def traverse_md(md: str, seek: str) -> str: ...
