from collections.abc import Callable
from typing import Any

from gamepack.BaseCharacter import BaseCharacter
from gamepack.MDPack import MDObj

from .EnergySystem import EnergySystem as EnergySystem
from .HeatSystem import HeatSystem as HeatSystem
from .MovementSystem import MovementSystem as MovementSystem
from .OffensiveSystem import OffensiveSystem as OffensiveSystem
from .SealSystem import SealSystem as SealSystem
from .System import System as System

class Mecha(BaseCharacter):
    description: dict[str, Any]
    speeds_at_seconds: list[int]
    _totalmass: float
    Movement: dict[str, MovementSystem]
    Energy: dict[str, EnergySystem]
    Heat: dict[str, HeatSystem]
    Offensive: dict[str, OffensiveSystem]
    Defensive: dict[str, System]
    Support: dict[str, System]
    Seal: dict[str, SealSystem]
    Sectors: dict[str, dict[str, Any]]
    _categories: list[str]
    loadouts: dict[str, list[System | str]]
    shutoff_counters: dict[str, int]
    _turn: int
    _current_speed: float
    _target_speed: float
    _fluxpool: float
    _pending_heat: float
    def __init__(self) -> None: ...
    @staticmethod
    def load_system_data(name: str, category: str) -> dict[str, Any]: ...
    @classmethod
    def from_mdobj(cls, mdobj: MDObj, flash_func: Callable[[str], None] | None = None) -> Mecha: ...
    @property
    def total_mass(self) -> float: ...
    @property
    def systems(self) -> dict[str, dict[str, System]]: ...
    def get_system(self, name: str) -> System | None: ...
    def speeds(self) -> dict[str, Any]: ...
    def to_mdobj(self) -> MDObj: ...
    def systems_mdobj(self) -> MDObj: ...
    def process_loadout(self, plaintext: str) -> list[System | str]: ...
    def fluxmax(self) -> float: ...
    def add_heat(self, amt: float) -> float: ...
    def tick_heat(self) -> dict[str, float]: ...
    def move_heat(self, source_name: str, target_name: str, amount: float) -> float: ...
    def energy_budget(self) -> float: ...
    def energy_total(self) -> float: ...
    def energy_demand(self) -> float: ...
    def energy_allocation(self, loadout: str | None = None) -> tuple[list[System], int]: ...
    def get_syscat(self, name: str) -> dict[str, System]: ...
    def fluxpool_max(self) -> float: ...
    def assign_heat(self, name: str, amount: float) -> tuple[float, str]: ...
    def use_system(self, systemtype: str, name: str, parameter: Any | None) -> float: ...
    def flux_baseload(self) -> float: ...
    @property
    def turn(self) -> int: ...
    @turn.setter
    def turn(self, value: int): ...
    @property
    def current_speed(self) -> float: ...
    @current_speed.setter
    def current_speed(self, value: float): ...
    @property
    def target_speed(self) -> float: ...
    @target_speed.setter
    def target_speed(self, value: float): ...
    @property
    def fluxpool(self) -> float: ...
    @fluxpool.setter
    def fluxpool(self, value: float): ...
    @property
    def pending_heat(self) -> float: ...
    @pending_heat.setter
    def pending_heat(self, value: float): ...
    def apply_event(self, event: dict[str, Any]): ...
    def apply_loadout(self, loadout_name: str): ...
    def replay(self, events: list[dict[str, Any]], turn_limit: int | None = None): ...
    def next_turn(self) -> dict[str, Any]: ...
    def projected_flux(self) -> float: ...
    def projected_energy(self) -> float: ...
    def current_top_speed(self) -> float: ...
    def projected_cooling(self) -> float: ...
    def energy_output(self) -> float: ...
