from typing import ClassVar, Self

import numpy as np
from _typeshed import Incomplete

logger: Incomplete

class DescriptiveError(Exception): ...

class DiceInterpretation:
    __functions: ClassVar[dict[str, str]]
    function: str
    dice: Dice
    def __init__(self, function: str, dice: Dice) -> None: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def resonance(self, resonator: int) -> int: ...
    @property
    def result(self) -> int | None: ...
    def roll_sel(self, sel: str) -> int: ...
    @property
    def name(self) -> str: ...
    def process_rerolls(self) -> tuple[list[int], str]: ...
    @staticmethod
    def botchformat(succ: int, antisucc: int) -> int: ...
    def roll_wodsuccesses(self) -> tuple[int, str]: ...
    def roll_v(self) -> str: ...
    @staticmethod
    def drop_n(x: list[int], n: int) -> list[int]: ...
    def roll(self, *, truncate: bool = True) -> DiceInterpretation: ...

class Dice:
    sign: int
    r: np.ndarray | None
    explosions: int
    explode: Incomplete
    literal: bool
    rolled: bool
    amount: Incomplete
    max: Incomplete
    sort: Incomplete
    rerolls: Incomplete
    def __init__(
        self,
        amount: np.ndarray | list[int] | float | None,
        sides: int,
        *,
        sort: bool = False,
        rerolls: int = 0,
        explode: int = 0,
    ) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str: ...
    def another(self) -> Dice: ...
    def roll(self, amount: int | None = None) -> Self: ...
    @classmethod
    def empty(cls) -> Dice: ...
