import re
from collections.abc import Callable
from typing import Any, TypeVar

_F = TypeVar("_F", bound=Callable[..., Any])

class DuplicateKeyError(Exception): ...
class PartialMatchError(Exception): ...

class RegexRouter:
    routes: dict[re.Pattern[str], Callable[[dict[str, str]], dict[str, str]]]
    def __init__(self) -> None: ...
    def register(self, route: re.Pattern[str]) -> Callable[[_F], _F]: ...
    def run(self, decide: str, require: bool) -> dict[str, Any]: ...

class DiceRegexRouter:
    @staticmethod
    def get_dice_router() -> RegexRouter: ...
