import re
from collections.abc import Callable as Callable

class DuplicateKeyError(Exception): ...
class PartialMatchError(Exception): ...

class RegexRouter:
    routes: dict[re.Pattern, Callable]
    def __init__(self) -> None: ...
    def register(self, route: re.Pattern): ...
    def run(self, decide, require) -> None: ...

class DiceRegexRouter:
    @staticmethod
    def get_dice_router() -> None: ...
