import re
from datetime import datetime
from pathlib import Path
from typing import Any, ClassVar, Self

from _typeshed import Incomplete

from gamepack.MDPack import MDObj

log: Incomplete

class WikiPage:
    live: bool
    page_cache: ClassVar[dict[Path, Self]]
    wikicache: ClassVar[dict[str, dict[str, list[str]]]]
    _wikipath: Path | None
    wikistamp: int
    clock_re: Incomplete
    save_msg_queue: list[str]
    title: Incomplete
    tags: Incomplete
    body: Incomplete
    links: Incomplete
    meta: dict
    last_modified: Incomplete
    file: Incomplete
    def __init__(
        self,
        title: str,
        tags: list[str],
        body: str,
        links: list[str],
        meta: dict | str,
        modified: float | None = None,
        file: Path | None = None,
    ) -> None: ...
    def md(self, *, sanitize: bool = False) -> MDObj: ...
    @classmethod
    def wikipath(cls) -> Path: ...
    @classmethod
    def set_wikipath(cls, path: Path): ...
    @classmethod
    def locate(cls, pagename: str | Path | None) -> Path | None: ...
    @classmethod
    def load_locate(cls, page: str, *, cache: bool = True) -> Self | None: ...
    @classmethod
    def load(cls, page: Path | None, *, cache: bool = True) -> Self | None: ...
    def save(self, author: str, page: Path | None = None, message=None): ...
    def save_overwrite(self, author, message=None) -> None: ...
    def save_low_prio(self, message) -> None: ...
    @classmethod
    def reload_cache(cls, page: Path): ...
    def cacheupdate(self) -> None: ...
    @classmethod
    def wikindex(cls) -> list[Path]: ...
    @classmethod
    def gettags(cls) -> None: ...
    @classmethod
    def getlinks(cls) -> None: ...
    @classmethod
    def updatewikicache(cls) -> None: ...
    @classmethod
    def cache_items(cls) -> None: ...
    def get_clock(self, name) -> re.Match | None: ...
    def change_clock(self, name, delta) -> Self: ...
    def tagcheck(self, tag) -> None: ...
    def render(self) -> Any: ...
    @classmethod
    def resolve_address(cls, address: str) -> str | None: ...

def delayed_push(repo, pushtime: datetime): ...

saveat: Incomplete

def commit_and_push(wikipath_val, file, commit_message: str): ...
def savequeue() -> None: ...
def start_savequeue() -> None: ...
