import re
from pathlib import Path
from typing import Any, ClassVar, Self

from _typeshed import Incomplete

from gamepack.Dice import DescriptiveError as DescriptiveError
from gamepack.MDPack import MDObj

__all__ = ["DescriptiveError", "WikiPage", "savequeue", "start_savequeue"]

class WikiPage:
    live: bool
    page_cache: ClassVar[dict[Path, WikiPage]]
    wikicache: ClassVar[dict[str, dict[str, list[str]]]]
    _wikipath: Path | None
    wikistamp: float
    clock_re: Incomplete
    save_msg_queue: list[str]
    title: Incomplete
    tags: Incomplete
    body: Incomplete
    links: Incomplete
    meta: dict[str, Any]
    last_modified: Incomplete
    file: Incomplete
    def __init__(
        self,
        title: str,
        tags: list[str],
        body: str,
        links: list[str],
        meta: dict[str, Any] | str,
        modified: float | None = None,
        file: Path | None = None,
    ) -> None: ...
    def md(self, *, sanitize: bool = False) -> MDObj: ...
    @classmethod
    def wikipath(cls) -> Path: ...
    @classmethod
    def set_wikipath(cls, path: Path) -> None: ...
    @classmethod
    def locate(cls, pagename: str | Path | None) -> Path | None: ...
    @classmethod
    def load_locate(cls, page: str, *, cache: bool = True) -> Self | None: ...
    @classmethod
    def load(cls, page: Path | None, *, cache: bool = True) -> Self | None: ...
    def save(self, author: str, page: Path | None = None, message: str | None = None) -> None: ...
    def save_overwrite(self, author: str, message: str | None = None) -> None: ...
    def save_low_prio(self, message: str) -> None: ...
    @classmethod
    def reload_cache(cls, page: Path) -> None: ...
    def cacheupdate(self) -> None: ...
    @classmethod
    def wikindex(cls) -> list[Path]: ...
    @classmethod
    def gettags(cls) -> dict[str, list[str]]: ...
    @classmethod
    def getlinks(cls) -> dict[str, list[str]]: ...
    @classmethod
    def updatewikicache(cls) -> None: ...
    @classmethod
    def cache_items(cls) -> None: ...
    def get_clock(self, name: str) -> re.Match[str] | None: ...
    def change_clock(self, name: str, delta: int) -> Self: ...
    def tagcheck(self, tag: str) -> bool: ...
    def render(self) -> Any: ...
    @classmethod
    def resolve_address(cls, address: str) -> str | None: ...

def savequeue() -> None: ...
def start_savequeue() -> None: ...
