from collections.abc import Iterable
from typing import Any, ClassVar

from _typeshed import Incomplete

from gamepack.MDPack import MDTable

def to_heatformat(data: dict[str, Any]) -> str: ...

class System:
    headers: ClassVar[list[str]]
    enablers: ClassVar[list[str]]
    disablers: ClassVar[list[str]]
    systype: str
    name: str
    errors: list[str]
    mass: float
    amount: float
    energy: float
    heats: dict[str, float]
    enabled: str
    activation_rounds: int
    boot_progress: int
    boot_roll: int | None
    breakpoints: list[int]
    keywords: list[str]
    current_heat: float
    _data: Incomplete
    def __init__(self, name: str, data: dict[str, Any]) -> None: ...
    def extract(self, key: str, default: str = "", *, req: bool = True) -> Any: ...
    def number(self, inp: Any, default: float = 0.0) -> float: ...
    @property
    def total_mass(self) -> float: ...
    def to_dict(self) -> dict: ...
    def get_headers(self) -> list[str]: ...
    @classmethod
    def as_table(cls, systems: Iterable[System]) -> MDTable: ...
    def use(self, parameter: Any | None) -> float: ...
    def reset_ephemeral(self) -> None: ...
    def is_active(self) -> bool: ...
    def is_booting(self) -> bool: ...
    def needs_roll(self) -> bool: ...
    def is_disabled(self) -> bool: ...
    def from_heatformat(self, inp: Any) -> dict[str, float]: ...
